apiVersion: v1
kind: Service
metadata:
  name: weave-yarn-bridge
  labels:
    app: weave-yarn-bridge
spec:
  type: ClusterIP
  selector:
    app: weave-yarn-bridge
  ports:
    - name: http
      port: 80
      targetPort: 8080
